### ISSUE TITLE
Repetition of URL's

### ISSUE THREAD

**Issue by chandanchawda** [yanc0/ozxygen#1]
When I run the following command:
ozxygen -baseurl "GET http://mytileserver.org/osm/" -z 18 -num 10 -minlat 48.5 -maxlat 49.2 -minlon 1.69 -maxlon 2.98 
I get the following response:

GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png
GET http://mytileserver.org/osm/18/132710/90242.png 

I don't know why the URL's are getting repeated. Can somebody help?

**Comment by chandanchawda** [comment]
We can close this one now! #2

**Comment by yanc0** [comment]
Great job !
